### ISSUE TITLE
[Events Page] Modal

### ISSUE THREAD

**Issue by Mykhol** [UoaWDCC/wdcc-cms#22]

**Comment by Pookie-Cookie** [comment]
As a user, I would like to be able to view more details on the event upcoming.

Expected Behaviour:
when clicking on an event card in the events page, the background should be dimmed while a new pop screen displays further info on the event (long text description) while retaining overview information.
There should be a cross in top right hand corner to exit this modal view.

Design: https://www.figma.com/file/5DfnuEchXBWLWqDUtw2kgR/Events---Draft?node-id=0%3A1
